openapi: 3.0.1
info:
  title: Auth Service API
  description: Auth Service API for Ticket Booking Microservices System
  version: v1.0.0
servers:
  - url: http://localhost:8085
    description: Generated server url
paths:
  /health:
    get:
      tags:
        - health-controller
      operationId: health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /api/v1/auth/login:
    post:
      tags:
        - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Unauthorized
  /api/v1/auth/refresh:
    post:
      tags:
        - auth-controller
      operationId: refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/auth/validate:
    get:
      tags:
        - auth-controller
      operationId: validateToken
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer access token
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateTokenResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
    AuthRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        username:
          type: string
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
    ValidateTokenResponse:
      type: string
      example: Token is valid
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: token_invalid
        message:
          type: string
          example: JWT token is invalid


