openapi: 3.0.1
info:
  title: Booking Service API
  description: Booking Service API for Ticket Booking Microservices System
  version: v1.0.0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  /api/v1/booking:
    post:
      tags:
        - booking-controller
      operationId: createBooking
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
components:
  schemas:
    BookingRequest:
      type: object
      properties:
        username:
          type: string
        eventId:
          type: integer
          format: int64
        ticketCount:
          type: integer
          format: int64
    BookingResponse:
      type: object
      properties:
        username:
          type: string
        eventId:
          type: integer
          format: int64
        ticketCount:
          type: integer
          format: int64
        totalPrice:
          type: number