DROP DATABASE IF EXISTS inventory_db;
DROP DATABASE IF EXISTS auth_db;
DROP DATABASE IF EXISTS order_db;

CREATE DATABASE IF NOT EXISTS inventory_db;
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS order_db;