DROP DATABASE IF EXISTS inventory_db;
DROP DATABASE IF EXISTS booking_db;
DROP DATABASE IF EXISTS order_db;

CREATE DATABASE IF NOT EXISTS inventory_db;
CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS order_db;